version: '3.9'

services:

  profiles:
    container_name: profiles
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: glimpse_profiles
      POSTGRES_USER: glimpse_profiles
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres
      - .\internal\adapters\postgres\migrations\tables.up.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge